apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: myapp
        image: https://hub.docker.com/repository/docker/sivaganesh1625977/myapp
        ports:
        - containerPort: 80
