apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - image: sivaganesh1625977/myapp:1.0.0
        name: javaapp
        ports:
        - containerPort: 8080
